### ISSUE TITLE
Place de l'instruction

### ISSUE THREAD

**Issue by xcregut** [hyalham/Devin#1]
https://github.com/hyalham/Devin/blob/1e39cccb32541b2a38d91d9d3f0319adc0f2a8a0/devin_3.3a.py#L18
1. Il faudrait sauter une ligne après cette instruction car le commentaire précédent ne concerne que ces deux instructions. 
2. Cette instruction devrait être avant l'instruction précédente.

**Comment by hyalham** [comment]
Fixed ligne 18 à 19
