### ISSUE TITLE
Incomplet et mal placé

### ISSUE THREAD

**Issue by xcregut** [hyalham/Devin#4]
https://github.com/hyalham/Devin/blob/1e39cccb32541b2a38d91d9d3f0319adc0f2a8a0/devin_3.3a.py#L34
Ici, il faudrait juste écrire "Trouvé".
Donner le nombre d'essais devrait être fait une fois sorti de la boucle pour bien montrer que c'est seulement à la fin de la partie.

**Comment by hyalham** [comment]
Fixed ligne 36 et 38
